### ISSUE TITLE
Code is expecting a column for every generator - this assumption is wrong

### ISSUE THREAD

**Issue by kiran-anand14** [kiran-anand14/transform#4]
TC_5 failing.

_ERROR - one or more columns are not matching with the transformer columns {set(self.columns) - set(generator_keys)}_

Generators in transformer is a superset of columns mentioned in transformer, so extra generator is not harmful. Moreover, this extra generator may be used for performing some intermediary calculation that will be used in another generator. It is perfectly fine not to include this generator's output in final list of columns.

**Comment by mahekshah5858** [comment]
Understood.
Thanks

**Comment by kiran-anand14** [comment]
Fixed, Thanks.
